import { Geist, Geist_Mono, Open_Sans, Aleo, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['600'],          // SemiBold
  style: ['italic'],        // Italic
  variable: '--font-open-sans',
});

const aleo = Aleo({
  subsets: ['latin'],
  weight: ['700'],
  style: ['italic'],
  variable: '--font-aleo',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--font-poppings'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`bg-blue-100 antialiased ${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${aleo.variable} ${poppins.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
